sudo: required
services:
- docker
env:
  global:
  - DOCKER_HUB_REPO_SLUG="gozynq/${TRAVIS_REPO_SLUG#*/}"
  - secure: "hEee0z4MihBalVp5HgbhXLZX/5/mgeNmmn4cBk/ekwwQuur4bLBCqmpyZ8Q7pNwQ9C/IPi1+Ch0w4zwrATD9L6x0cnNKl1ksRIQWBp9lfNSbuUU2pCu8K8PU56bwdvG13ge/MUSMcIo/yNA0/vSilIpTMUKH6dlAPJKc/P38xBV4Au4M93QH3uMXi205iqJiygGcX2CYTTBSDtkrGSJ3QJ73m+9DQE+sbXO525OA8VqSCtC8qF6s+l7FeS8UZDM08F7uQVi92/vO61g7urrz4kYkBouUB4wmkaqPpKPvlwLBkQgo8+wEnucjX26Rko5eY7nH/06a88xfIxdPgQb6i9gBGV0Wrb/9XekGfi0MVPaOq2sLPqeNATWGzAzUCKea+s1xjguJBt8G5/DxPx+uRQCopMSEpbQ8WKXdhq0MnXYfH8fA9AsqwYrwUpJhylTwKXr/4xEcQ/HRc6JQkqWHBABFEzb/Wc9NmXI3XcvspEegLjrDUOUCcSQINHXmVP9a+wofsBOJljgrRb3grN3Nb9jlGbDnBRK7m84Oa2lgUv+ghqf8Z87LneKFH1NQBxQm4HCRFPhmv7y2SxZtDHzJbgCzbLy/TSmgzcYt3/XXh3gBq/beCP6RuJPpyg8ztF0VDjgSV48f+tHLVsQAiftW0XlIQG2IHpkHKoNSM39oVSQ=" #DOCKER_EMAIL
  - secure: "KT9ODBfgpnZB/c1sfp7hcIjSyTniV/q5EiSufp//vE3YR1vfvJFAlM2dGx/ue9xU1u9W78w3AqlwO6JeY6b7Nsf0fv5FqDSHhgXQIbaIQbVOJCNx6AMiasC6AsQg+v4r0YRSh07llQrvCK8hvsRwOwF1KRVE9sUuVKU0EZz91PA/+nxokCnh4OT4eDFKKW2tDKWmDlEdlid6FPoH32V4VTW14NvF0PqQV6dx6SMV4yYP3I4zucV5QnrT9QJOtR+lwQ8+nVVyG8TYNlPk8P6XG1GDuaFRyAk1iMaPIIYzfAyI9vZiaSwuYZQxruPr5S2HDmYMxSWSBZbqjWvTc2+O7fs9SS6TffquGibG9cyj3vSq5jF+xhXILi88z6zlxTaAuJH9kyVhtElN/kN5Jp5LCDxUpLuyEsrtDhqtptrCnXzkXDq8lESwa1+bR4s0neGndjVluOz4qJ7Vt6SXNjpKoK0zvNlZqCk6n7JuaWdUo4DaWI18RcVRAb/f7h+DeZ3RnwWQvnoQQNVy2Rw33079sj130GOSUnuFVAiZXIpwkGXRK5mxNVq6ZIADVcOuCtj+ZWq5TnVtiP6wL7IPQNI6QeLvErs0OIIv/Y5Bpm/n9wDls567Onr9whMQuwz758PJIKn2XFqWZvJwb2pEwT8lsaJmgs9bJLYdP6m0ps/Ss8w=" #DOCKER_USER
  - secure: "ORIMWaEG9hfjA3oE1XulDAKoKpBTdU/ohPSQl1Bw+65NyuLDPsuHnd3A4dtScGuBrz36XtHkB/seF0t09QVegeNrAbDm3WrTBoU6fBlgoTkNZtYsdYstD1mJ9tqJ538rDRJzNdzi0iL2P+kM0eyznlRm8ITHqOXa6tnVhBKDXX8feL8Sm6WV75ehNh2MAUacE89u14XY5iMofbL+9nV3bLsP+SoLhONP13zmuRTPtOHdI+klILFIm8Uih9GIBOAN5iIGtADfNseD/41MiowWMObifV4e1AFXKdKDyK3mmOJobhIsRpbWuXaODXXTLsc6HU9eHZQ5H/8Dt9zYGgBKakD/VLscnpVG8MzN2net6IY/ZD7Lecn5M8NKEQaIkPoISS24Ll8awFq3lXEI1Xc/6HqIj4+PKe28WhRxawMpqoSkY/S30Rvtn6xdpGxIRKpdX8cjlgEUkFK+MWCWVPMV3T2WJkJmZd3jxf0eZIUIj8DpQkZnKjRkGS+9M1+GioKVAhceqgQMdhB2gVghfZpOeZK/WgGThQriDIvwtBwa42VgOOhky196JYH/CgrO/C5WAi37NLxzbbS5GzkLqOfG5aUOCpgkowkh+ZsMipB9FHoJ+DKfXioIkfoJObYNVGGQ1Q1MRX3aZlGK8XUsYknC0+befkgQ6IdTjho9n2pkbYE=" #DOCKER_PASS
before_install:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
script:
# build image
- docker build -t ${DOCKER_HUB_REPO_SLUG}:build .
# test image
- docker run -id --name build ${DOCKER_HUB_REPO_SLUG}:build sh
- export NUMPY_VERSION=`docker exec build env|grep NUMPY_VERSION|awk -F = '{print $2}'`
- >
  if [ "${TRAVIS_BRANCH}" != "master" ]; then
    docker exec build python3 -m pip install --verbose numpy==${NUMPY_VERSION}
  fi
- >
  if [ "${TRAVIS_BRANCH}" != "master" ]; then
    docker exec build python3 -m pip wheel numpy
  fi
after_success:
# push image
- >
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker login -e "${DOCKER_EMAIL}" -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
    docker push ${DOCKER_HUB_REPO_SLUG}
  fi
